### DISCUSSION TITLE
MergerFS in Docker on macOS?

### DISCUSSION THREAD

**Discussion by BEisem** [trapexit/mergerfs#1259] [Q&A]
I understand that MergerFS does not work on macOS (according to my research ... if this has changed, please let me know!)

So I've been trying to get it to run in Docker on macOS, hoping maybe that would be a workaround.

I got it to work, sort of. I can access the merged directory from within the docker container, if I `exec` into the container. But the merged directory is empty if I try to access it from the host OS. I can't figure out why this is happening.

Here is the docker run command I'm using:

```
docker run --rm \
    --init \
    --name=mergerfs \
    --security-opt=apparmor:unconfined \
    -v /Users/bink/mnt/dropbox:/dropbox \
    -v /Users/bink/mnt/feeder:/feeder \
    -v /Users/bink/data/movies:/movies:shared \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    ghcr.io/hotio/mergerfs /dropbox:/feeder /movies -o rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true,nonempty
```

As I said, if I exec into the container and go to the `/movies` directory, it lists the contents of the merged directory. However outside the container, if I go to `/Users/bink/data/movies`, it is empty.

I realize this isn't directly a mergerfs problem, but I was hoping someone here might have some insight. Any ideas?

**Comment by KyleSanderson** [comment]
rslave

**Reply by BEisem** [reply]
I've tried to research this, but still can't get anything to work. I've tried changing the following: `-v /Users/bink/data/movies:/movies:rslave \`

I also tried `--mount type=bind,source=/Users/bink/data/movies,target=/movies,bind-propagation=rslave \`

But the results are the same. Can you give me some more insight? Google is failing me at the moment...

**Reply by KyleSanderson** [reply]
https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation

you could also try shared.

**Comment by saltydk** [comment]
Tried just mounting /Users/bink/data to /data or something like that and then doing /data/movies?

**Comment by ahm99** [comment]
Hello, 
Any luck solving the issue?

I'm facing the exact same thing
docker compose:
 

> mergerfs:
    image: hvalev/mergerfs:latest
    container_name: mergerfs
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - PUID=501
      - PGID=20
    volumes:
      - /Volumes/NVMe/Docker/mergerfs:/config
      - /Volumes/disk1/Data:/disks/disk1
      - /Volumes/disk2/Data:/disks/disk2
      - /Volumes/disk-3/Data:/disks/disk3
      - /Volumes/disk-4/Data:/disks/disk4
      - /Volumes/disk-1/Merged:/merged:shared
    restart: always

I can see the merged folded in the container terminal with all of the disks contents, and I can see that merged folder is created in may macOS finder, but it's empty

**Reply by trapexit** [reply]
mergerfs is not supported on MacOS. Docker on Mac is just a Linux VM. Binding a volume into that VM and using mergerfs to combine them *in the VM* will have no impact on the MacOS system. At most maybe you can share the volume between containers and export it via Samba or other remote filesystem.

**Reply by ahm99** [reply]
I tried sharing a volume between containers, actually this is what I want (qbit container to talk to radarr & sonarr containers)
but I see the same thing. the volume doesn't get the merged files and the other containers don't see them. even though if I create a file in a container I can see it in the other and in the volume

in mergerfs container:
```
/ # ls merged/
Library   Torrents
```

in other containers:
```
root@448298d1f591:/# ls merged_data/
test.txt (this is the file I created)
```

this is my setup:
```
volumes:
  Merged_Data:
    external: true
    name: Merged_Data

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - XXXX:XXXX
      - XXXX:XXXX
      - XXXX:XXXX/udp
    environment:
      - PUID=501
      - PGID=20
      - WEBUI_PORT=XXXX
      - TORRENTING_PORT=XXXX
    volumes:
      - Merged_Data:/merged_data:shared
      - /Volumes/NVMe/Docker/qbittorrent:/config
    restart: unless-stopped

  mergerfs:
    image: hvalev/mergerfs:latest
    container_name: mergerfs
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - PUID=501
      - PGID=20
    volumes:
      - /Volumes/NVMe/Docker/mergerfs:/config
      - /Volumes/disk_1/Data:/disks/disk_1
      - /Volumes/disk_2/Data:/disks/disk_2
      - /Volumes/disk_3/Data:/disks/disk_3
      - /Volumes/disk_4/Data:/disks/disk_4
      - Merged_Data:/merged:shared
    restart: unless-stopped
```


```
/ # mergerfs -V
mergerfs v2.40.2-2-gdd987db6
```

```
/ # cat /etc/fstab
/dev/cdrom      /media/cdrom    iso9660 noauto,ro 0 0
/dev/usbdisk    /media/usb      vfat    noauto,ro 0 0
```

```
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 109.7G      4.2G     99.9G   4% /
tmpfs                    64.0M         0     64.0M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
/run/host_mark/Volumes
                        228.3G    204.0G     24.3G  89% /config
/dev/vda1               228.3G    204.0G     24.3G  89% /merged
/run/host_mark/Volumes
                        228.3G    204.0G     24.3G  89% /disks/disk_3
/run/host_mark/Volumes
                        228.3G    204.0G     24.3G  89% /disks/disk_4
/run/host_mark/Volumes
                        228.3G    204.0G     24.3G  89% /disks/disk_1
/run/host_mark/Volumes
                        228.3G    204.0G     24.3G  89% /disks/disk_2
/dev/vda1               109.7G      4.2G     99.9G   4% /etc/resolv.conf
/dev/vda1               109.7G      4.2G     99.9G   4% /etc/hostname
/dev/vda1               109.7G      4.2G     99.9G   4% /etc/hosts
1:2:3:4                 228.3G    204.0G     24.3G  89% /merged
```
