### ISSUE TITLE
Extremely slow samba share transfer

### ISSUE THREAD

**Issue by amrap030** [trapexit/mergerfs#1059]
Hello together,

I am using mergerfs on my homeserver and wanted to setup Samba, to read and transfer files from my Macbook from the homeserver. However, I noticed that the speed is extremely slow. It is really only like 2KB/s, so there must be something completely wrong.

Some background information on my setup:

I am using ansible to create the mergerfs array. I have 2 6GB WD MyBook drives, one as the data drive (xfs) and one as parity drive (xfs). Then I have one additional Samsung 970 EVO Plus 1GB NVME drive (ext4) as the cache drive. The following was used to create the arrays:

```yml
- name: Mount the mergerfs cached array
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/storage_cache:/mnt/storage_slow
    opts: category.create=lfs,direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

- name: Mount the mergerfs array
  mount:
    name: "{{ mergerfs_root }}_slow"
    src: /mnt/data*
    opts: direct_io,defaults,allow_other,minfreespace=500G,fsname=mergerfs_slow,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

- name: Mount the mergerfs cache only array
  mount:
    name: "{{ cache_root }}"
    src: /mnt/cache*
    opts: direct_io,defaults,allow_other,fsname=mergerfs_cache,category.create=mfs
    fstype: fuse.mergerfs
    state: mounted
  when: cache_disks[0] is defined
```

In summary, I have now one mount named `storage` that is composed of the `storage_slow` (data drives ) and `storage_cache` (cache drive).

I already did some recommended benchmarks:

1. Write: `dd if=/dev/zero of=/mnt/{mount}/1GB.file bs=1M count=1024 oflag=nocache conv=fdatasync status=progress`

`/mnt/storage`:

```
811597824 bytes (812 MB, 774 MiB) copied, 1 s, 811 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 1,69748 s, 633 MB/s
```

`/mnt/storage_slow`:

```
1024+0 records in
1024+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 7,13901 s, 150 MB/s
```

`/mnt/storage_cache`:

```
1052770304 bytes (1,1 GB, 1004 MiB) copied, 1 s, 1,1 GB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 1,38544 s, 775 MB/s
```

2. Read: `dd of=/dev/zero if=/mnt/{mount}/1GB.file bs=1M count=1024 iflag=nocache conv=fdatasync status=progress`

`/mnt/storage`:

```
1020264448 bytes (1,0 GB, 973 MiB) copied, 3 s, 340 MB/s
dd: fsync failed for '/dev/null': Invalid argument
1024+0 records in
1024+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 3,15807 s, 340 MB/s
```

`/mnt/storage_slow`:

```
dd: fsync failed for '/dev/null': Invalid argument
1024+0 records in
1024+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 0,788549 s, 1,4 GB/s
```

`/mnt/storage_cache`:

```
dd: fsync failed for '/dev/null': Invalid argument
1024+0 records in
1024+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 0,642096 s, 1,7 GB/s
```

For the samba  configuration, I am using this:

```
multicast dns register = No
log level = 1
socket options = TCP_NODELAY SO_RCVBUF=65536 SO_SNDBUF=65536
read raw = yes
write raw = yes
max xmit = 65535
dead time = 15
getwd cache = yes
client min protocol = SMB2
client max protocol = SMB3
ntlm auth = yes 
```

I have absolutely no idea how to troubleshoot this. I would be glad if someone can help, because 2KB/s of transfer is absolutely not usable.
