### ISSUE TITLE
Nextcloud in docker targeting mergerfs pool not working

### ISSUE THREAD

**Issue by LegendaryB** [trapexit/mergerfs#679]
General description
===================
Nextcloud as docker container is not usable with mergerfs pool.

Expected behavior
=================
It just works.

Actual behavior
===============
Nextcloud docker container is working fine when pointed directly to a path on the hdd. When pointing to the storage pool it is not.

**Precise** steps to reproduce the behavior
===========================================

Docker-Compose file:
```
version: '3'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /mnt/pool/docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=ROOTPW

  app:
    container_name: nextcloud-app
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /mnt/pool/docker/nextcloud/app:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - db

  web:
    container_name: nextcloud-nginx
    build: ./web
    restart: always
    ports:
      - 80:80
    volumes:
      - /mnt/pool/docker/nextcloud/app:/var/www/html:ro
    depends_on:
      - app 
```

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
```
mergerfs version: 2.28.3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29
```

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sdb2 during installation
UUID=58fe345c-5b2d-46e0-8bab-caa64446ece9 /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sdb1 during installation
UUID=7BC4-9647  /boot/efi       vfat    umask=0077      0       1
# swap was on /dev/sdb3 during installation
UUID=ae88990a-d397-4fdc-971c-f5af48711ad3 none            swap    sw              0       0

# pool drives
UUID=d22429cf-a98e-4e0e-9fee-8a1ff176f566       /mnt/data-01-sda        ext4    defaults        0       0
UUID=b4ee7086-c602-4f8e-8689-7e080165fb85       /mnt/data-02-sdc        ext4    defaults        0       0
UUID=538e4c74-1302-4915-ac52-048ab0b59a06       /mnt/data-03-sdd        ext4    defaults        0       0

# pool
/mnt/data*    /mnt/pool       fuse.mergerfs  defaults,allow_other,use_ino,fsname=mergerFS-pool   0       0
```

* [x] Linux version: `uname -a`
`Linux sirius 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`

* [x] Versions of any additional software being used
```
Docker version 19.03.5, build 633a0ea838
docker-compose version 1.21.0
```

* [x] List of drives, filesystems, & sizes: `df -h`
```
udev            7,8G       0  7,8G    0% /dev
tmpfs           1,6G     11M  1,6G    1% /run
/dev/sdb2        96G    8,5G   83G   10% /
tmpfs           7,9G       0  7,9G    0% /dev/shm
tmpfs           5,0M       0  5,0M    0% /run/lock
tmpfs           7,9G       0  7,9G    0% /sys/fs/cgroup
mergerFS-pool   8,1T    367G  7,3T    5% /mnt/pool
/dev/sdb1       511M     12M  500M    3% /boot/efi
/dev/sdd1       2,7T    361G  2,2T   14% /mnt/data-03-sdd
/dev/sda1       2,7T    4,8G  2,6T    1% /mnt/data-01-sda
/dev/sdc1       2,7T    683M  2,6T    1% /mnt/data-02-sdc
tmpfs           1,6G       0  1,6G    0% /run/user/1000
```
